### ISSUE TITLE
[WANT] 매도/매수 내역 반환값 id 추가

### ISSUE THREAD

**Issue by sw-devr** [screeningHumanity/TMT-BE-TradeServer#18]
## 요청 구분
- [x] 신규 요구 사항 발생
- [ ] 수정 요청

## 요청 내용
![image](https://github.com/screeningHumanity/TMT-BE-TradeServer/assets/141290308/6350e545-a2ae-4718-9714-ae1d9193d7ae)
해당 반환값에서 id를 추가해서 반환부탁드립니다 !

**Comment by KangBaekGwa** [comment]
내용 확인 했습니다.
