### ISSUE TITLE
[WANT] MemberLog 에 존재하는 TotalAmount 수정요청

### ISSUE THREAD

**Issue by hoontaepark** [screeningHumanity/TMT-BE-TradeServer#24]
## 요청 구분
- [x] 신규 요구 사항 발생
- [ ] 수정 요청

## 요청 내용
주식 매도 수량이 0에 도달할때, TotalAmount 도 0으로 수정 부탁드립니다.

**Comment by KangBaekGwa** [comment]
내용 확인했습니다.
